### PR TITLE
Issue 3

### LINKED ISSUE #3: If the timestamp of the files is exactly the same the sort function error

### PR DESCRIPTION
**Pull request by kpanic**
This might fix #3 
I was able to reproduce it only via tests.
@rizafahmi could you double check if it works now before merging? thanks!

### CODE REVIEW

**Comment by rizafahmi** [comment]
Still same error :cry:

**Comment by kpanic** [comment]
eheh @rizafahmi I added also a `.travis.yml` file
What's the output of 
`Files.Sort.newest(["filename.md", "basicfp.md"])` in your setup? Please add more files to the list if needed
(Fingers crossed) :)

**Comment by rizafahmi** [comment]
@kpanic thanks for `travis.yml` file. I've never been using travis before :+1: 

I can do two files `Files.Sort.newest`. But when I add one more file, it error.

```
Files.Sort.newest(["filename.md", "basicfp.md"])
["basicfp.md", "filename.md"]
iex(2)> Files.Sort.newest(["filename.md", "basicfp.md", "elixirdose_flatfileblog.md"])
** (FunctionClauseError) no function clause matching in Files.Sort.sort/1
    (dds_blog) lib/dds_blog/files_sort.ex:20: Files.Sort.sort([%{filename: "elixirdose_flatfileblog.md", timestamp: 1422513250}])
    (dds_blog) lib/dds_blog/files_sort.ex:32: Files.Sort.sort/1
```

**Comment by kpanic** [comment]
I think I finally understood the issue, will work on it :) thanks a lot!

**Comment by kpanic** [comment]
@rizafahmi I pushed the new changes, this should work

**Comment by rizafahmi** [comment]
Awesome job @kpanic !

**Pull request merged**
